var x;
x = 'Welcome to Type Script';
console.log(x);
var myage = 25;
var myname = 'HCL';
var isEligible = true;
var data;
var data1;
var data2;
console.log("My Name is " + myname);
console.log("My Age is " + myage);
console.log("My Eligibility is " + isEligible);
console.log("My data is " + data);
console.log("" + data1);
console.log("" + data2);
data = 10;
console.log("Now data is " + data);
data = 'Chennai';
console.log("Now data is " + data);
